language: java
sudo: false
install: true

addons:
  sonarcloud:
    organization: "hyagosouzza"
    token:
      secure: "45413d43d2dd317918b1906ea0c6ca4ff7afb7fe"

jdk:
  - oraclejdk8

script:
  - ./gradlew sonarqube
